version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@<<pipeline.parameters.dev-orb-version>>

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

executors:
  debian:
    docker:
      - image: cimg/base:edge
  alpine:
    docker:
      - image: alpine
  mac:
    macos:
      xcode: 12.5.1

jobs:
  integration-test_full:
    parameters:
      env:
        type: executor
        default: debian
    executor: <<parameters.env>>
    steps:
      - checkout
      - shellcheck/install
      - run:
          name: Verify Shellcheck install
          command: shellcheck -V
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086
          dir: ./src/scripts

workflows:
  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - bats/run:
          setup-steps:
            - shellcheck/install
          path: src/tests

      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run

      - orb-tools/publish-dev:
          orb-name: circleci/shellcheck
          requires: [ hold-for-dev-publish ]
          context: orb-publisher

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
          context: orb-publisher

  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086
          dir: ./src/scripts
      - integration-test_full:
          matrix:
            parameters:
              env:
                - debian
                - mac
                - alpine

      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/shellcheck
          context: orb-publisher
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: orb-publisher
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: 40:21:b7:d7:fe:ea:dd:80:ca:c8:34:7a:37:b4:b4:d2
          requires:
            - shellcheck/check
            - integration-test_full
          filters:
            branches:
              only: master
